package github

import (
	"context"
	"fmt"
	"strings"
	"time"

	gh "github.com/google/go-github/v68/github"
)

// TokenStatus represents token usage for a single agent.
type TokenStatus struct {
	Used  int
	Limit int
}

// CreatePMComment posts a PM-formatted comment on an issue.
func (c *GitHubClient) CreatePMComment(ctx context.Context, issueNum int, phase, content string, tokenStatus map[string]TokenStatus) error {
	var statusParts []string
	for name, ts := range tokenStatus {
		statusParts = append(statusParts, fmt.Sprintf("%s=%dK/%dK", name, ts.Used/1000, ts.Limit/1000))
	}
	tokenLine := strings.Join(statusParts, " | ")

	body := fmt.Sprintf(`### @PM (Project Manager)

**Phase**: %s

%s

---
**Token Status**: %s
**Auto-generated by MAAO v0.1.0** | %s`,
		phase,
		content,
		tokenLine,
		time.Now().UTC().Format(time.RFC3339),
	)

	_, _, err := c.Client.Issues.CreateComment(ctx, c.owner, c.repo, issueNum, &gh.IssueComment{
		Body: gh.String(body),
	})
	return err
}

// CreateAgentComment posts an agent-formatted comment on an issue.
func (c *GitHubClient) CreateAgentComment(ctx context.Context, issueNum int, agentName, replyTo, content string, tokensUsed int) error {
	var replyLine string
	if replyTo != "" {
		replyLine = fmt.Sprintf("\n> Replying to @%s\n", replyTo)
	}

	body := fmt.Sprintf(`### @%s%s

%s

---
**Tokens used**: %dK
**Auto-generated by MAAO v0.1.0** | %s`,
		agentName,
		replyLine,
		content,
		tokensUsed/1000,
		time.Now().UTC().Format(time.RFC3339),
	)

	_, _, err := c.Client.Issues.CreateComment(ctx, c.owner, c.repo, issueNum, &gh.IssueComment{
		Body: gh.String(body),
	})
	return err
}
