package notify

import (
	"bytes"
	"fmt"
	"net/smtp"
	"strings"
	"text/template"
	"time"
)

type EmailNotifier struct {
	smtpHost string
	smtpPort int
	username string
	password string
	to       string
}

func NewEmailNotifier(host string, port int, username, password, to string) *EmailNotifier {
	return &EmailNotifier{
		smtpHost: host,
		smtpPort: port,
		username: username,
		password: password,
		to:       to,
	}
}

type CompletionReport struct {
	RepoURL     string
	Duration    time.Duration
	IssuesCount int
	PRsMerged   int
	TokensUsed  map[string]int
	Errors      []string
}

var emailTemplate = template.Must(template.New("completion").Parse(`Subject: [MAAO] Workflow Complete - {{.RepoURL}}
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
From: {{.From}}
To: {{.To}}

MAAO Workflow Completion Report
================================

Repository: {{.Report.RepoURL}}
Duration:   {{.Report.Duration}}
Issues:     {{.Report.IssuesCount}}
PRs Merged: {{.Report.PRsMerged}}

Token Usage:
{{- range $agent, $tokens := .Report.TokensUsed}}
  {{$agent}}: {{$tokens}}
{{- end}}

{{- if .Report.Errors}}

Errors:
{{- range .Report.Errors}}
  - {{.}}
{{- end}}
{{- end}}

---
Generated by MAAO (Multi-Agent AI Orchestrator)
`))

func (n *EmailNotifier) SendCompletion(report CompletionReport) error {
	var buf bytes.Buffer
	data := struct {
		From   string
		To     string
		Report CompletionReport
	}{
		From:   n.username,
		To:     n.to,
		Report: report,
	}

	if err := emailTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("rendering email template: %w", err)
	}

	addr := fmt.Sprintf("%s:%d", n.smtpHost, n.smtpPort)
	auth := smtp.PlainAuth("", n.username, n.password, n.smtpHost)

	recipients := strings.Split(n.to, ",")
	if err := smtp.SendMail(addr, auth, n.username, recipients, buf.Bytes()); err != nil {
		return fmt.Errorf("sending email: %w", err)
	}

	return nil
}
